python3 run_baseline.py ../data/test_data/cam_01.mp4 --config_cam configs/cam1.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_02.mp4 --config_cam configs/cam2.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_03.mp4 --config_cam configs/cam3.yaml --model models/troi_toi.pth
python3 run_baseline.py ../data/test_data/cam_04.mp4 --config_cam configs/cam4.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_05.mp4 --config_cam configs/cam5.yaml --model models/troi_toi.pth
python3 run_baseline.py ../data/test_data/cam_06.mp4 --config_cam configs/cam6.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_07.mp4 --config_cam configs/cam7.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_08.mp4 --config_cam configs/cam8.yaml --model models/troi_toi.pth
python3 run_baseline.py ../data/test_data/cam_09.mp4 --config_cam configs/cam9.yaml --model models/detT2_day.pth
python3 run_baseline.py ../data/test_data/cam_10.mp4 --config_cam configs/cam10.yaml --model models/detT2_day.pth
python3 run_baseline.py ../data/test_data/cam_11.mp4 --config_cam configs/cam11.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_12.mp4 --config_cam configs/cam12.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_13.mp4 --config_cam configs/cam13.yaml --model models/troi_toi.pth
python3 run_baseline.py ../data/test_data/cam_14.mp4 --config_cam configs/cam14.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_15.mp4 --config_cam configs/cam15.yaml --model models/troi_toi.pth
python3 run_baseline.py ../data/test_data/cam_16.mp4 --config_cam configs/cam16.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_17.mp4 --config_cam configs/cam17.yaml --model models/detT2_night.pth
python3 run_baseline.py ../data/test_data/cam_18.mp4 --config_cam configs/cam18.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_19.mp4 --config_cam configs/cam19.yaml --model models/troi_toi.pth
python3 run_baseline.py ../data/test_data/cam_20.mp4 --config_cam configs/cam20.yaml --model models/troi_toi.pth
python3 run_baseline.py ../data/test_data/cam_21.mp4 --config_cam configs/cam21.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_22.mp4 --config_cam configs/cam22.yaml --model models/troi_toi.pth
python3 run_baseline.py ../data/test_data/cam_23.mp4 --config_cam configs/cam23.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_24.mp4 --config_cam configs/cam24.yaml --model models/troi_sang.pth
python3 run_baseline.py ../data/test_data/cam_25.mp4 --config_cam configs/cam25.yaml --model models/troi_sang.pth