CAM:
    NAME: "CAM_23"
    NUMBER_MOI: 2
    ROI_DEFAULT: [[207, 418], [803, 283], [1153, 368], [1090, 690]]
    TRACKING_ROI: [[207, 418], [803, 283],[961,321],[1005,277],[1158,308], [1153, 368], [1090, 690],[583,536],[369,629],[55,482]]
    # MOI1: [[549, 144], [297, 505]]
    # MOI2: [[925, 487], [715, 144]]
    LINE1: [[402,371], [592,457]]
    LINE2: [[876,344], [1140,417]]
    LINE: [[[402,371], [592,457]],[[876,344], [1140,417]]]
    
    # for kalman filter - kalman_filter.py
    _STD_WEIGHT_POSITION: 12         # inverse of _std_weight_position
    _STD_WEIGHT_VELOCITY: 100         # inverse of _std_weight_velocity
  
    # config for tracker - tracker.py
    MAX_IOU_DISTANCE: 0.85
    MAX_AGE: 8
    N_INIT: 2