CAM:
    NAME: "CAM_04"
    NUMBER_MOI: 2
    #ROI_DEFAULT: [[1, 567], [484, 171], [756, 164], [910, 719], [0, 718]]
    ROI_DEFAULT: [[1, 567], [295,325], [801,324], [862,549]]
    TRACKING_ROI: [[1, 567], [382,254],[593,253],[617,160],[766,160], [782,246], [862,549],[448,555],[424,720],[3,720]]
    MOI1: [[587,160], [286, 716]]
    MOI2: [[609, 716], [663, 159]]
    MOI: [[[587,160], [286, 716]], [[609, 716], [663, 159]]]

    LINE1: [[56,514], [502,518]]
    LINE2: [[823,394],[543,395]]
    LINE: [[[56,514], [502,518]], [[823,394],[543,395]]]

    
  # for kalman filter - kalman_filter.py
    _STD_WEIGHT_POSITION: 12         # inverse of _std_weight_position
    _STD_WEIGHT_VELOCITY: 100         # inverse of _std_weight_velocity

    # config for tracker - tracker.py
    MAX_IOU_DISTANCE: 0.85
    MAX_AGE: 3
    N_INIT: 1
    THRESHOLD_AREA: 0.25

    #MOI2 +22
    FRAME_MOI1: 4
    FRAME_MOI2: 22
    FRAME_MOI: [4,22]