CAM:
  NAME: "CAM_09"
  NUMBER_MOI: 1
  ROI_BTC: [[87,425], [540,279], [1156, 303], [1262, 621]]
  ROI_DEFAULT: [[87,425], [540,279], [1156, 303], [1262, 621]]
  TRACKING_ROI: [[238, 454], [721, 251], [1160, 278],[1262, 621]]
  MOI1: [[655, 575], [943, 274]]
  MOI: [[[655, 575], [943, 274]]]
  LINE1: [[564,307], [1177,368]]
  LINE: [[[564,307], [1177,368]]]

  # for kalman filter - kalman_filter.py
  _STD_WEIGHT_POSITION: 12         # inverse of _std_weight_position
  _STD_WEIGHT_VELOCITY: 100         # inverse of _std_weight_velocity
  # config for tracker - tracker.py
  MAX_IOU_DISTANCE: 0.85
  MAX_AGE: 3
  N_INIT: 1
  THRESHOLD_AREA: 0.25
  #MOI1 +6
  FRAME_MOI1: 6
  FRAME_MOI: [6]

  # distance for auto estimate frame
  DISTANCE_ROI: [260]
  TEST1 : [[238, 454], [694, 284], [1156, 306], [1262, 621]]
  ROI_SPLIT_REGION: [[[238, 454], [694, 284], [1156, 306], [1262, 621]]]
  D_THRESHOLD: [90]

  # point-in-moi-region threshold
  PIM_THRESHOLD: 0.1