<<<<<<< HEAD
YOLOV3:
  CFG: "configs/yolov3.cfg"
  WEIGHTS: "models/yolov3.weights"
=======
YOLOV3:
  CFG: "configs/yolov3.cfg"
  WEIGHTS: "models/yolov3_Hieu_13000_0.65.weights"
>>>>>>> master
  CLASS_NAMES: "data/traffic.names"